### ISSUE TITLE
생각 수정/삭제

### ISSUE THREAD

**Issue by w36495** [w36495/about#67]
### Todo
- [ ] 생각 화면 내 appbar 의 menu 클릭 시, 수정/삭제 다이얼로그 표시
- [ ] 생각 수정 기능 구현
- [ ] 생각 삭제 기능 구현

**Comment by w36495** [comment]
이슈종료 (#70 )
